{% set name = "CLBlast" %}
{% set version = "1.6.1" %}
{% set sha256 = "e68d026108447cab53cb18d473b4363ab3958d7c8f97c522bbee1651069eec66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNugteren/CLBlast/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - ocl-icd                    # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
  run:
    - ocl-icd                    # [linux]
    - khronos-opencl-icd-loader  # [win or osx]

test:
  commands:
    # Check files
    - test -f "${PREFIX}/include/clblast.h"           # [unix]
    - test -f "${PREFIX}/lib/libclblast.so"           # [linux]
    - test -f "${PREFIX}/lib/libclblast.dylib"        # [osx]
    - if not exist %LIBRARY_INC%\\clblast.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\clblast.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\clblast.lib exit 1  # [win]

about:
  home: https://github.com/CNugteren/CLBlast
  license: Apache-2.0
  license_file: LICENSE
  summary: CLBlast is a modern, lightweight, performant and tunable OpenCL BLAS library written in C++11

extra:
  recipe-maintainers:
    - jakirkham
    - isuruf
