appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
matrix:
- []
- - [OSX_VARIANT, native]
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: q+tZNIp46GEwJtKlvrI4WEOWLgUXg0QGR1ygHFAn4QXUySH9/SkUhM3u1UsN+np9YbEx4XTwhVsfhdi7Rp03Llb5AIrdzFVLK/ycQJc122Mufiin+C1wgTO8/V8m03V57nUiHRW7ACZdsyU3Awqu1Ncsh7xehSFmWYpGARHJZV9wt3TAn2S0MFrpy2veJl+08R2qNBGnIXVXqs7TwBzLBFWf8g0XV/MLpR3psgXvihVINzmiJJvyn2PqQbdSCE4Aac0B1cngiCMG9LwLto52Hmqt/D5Sl8nnz4vnuJtx1lz3Nh6FD7bU5obuJXVD7CXWWIHwTx/sCDYf9qmCpT5Fl+h9VxvudEaLyWTi8v0r5kN7gocpri69/vKSRBIQLTWe51KAW7qCiZ+Kb/o9N4bgCnPkI2pLVmruTtLiF5g5zg5oFxfYX+2XzTDcnwO56Vpy9l2OEstFPY7t67n8fLS43Vd0N482PtnVJrdkH6tn4rRawQNLeQwZ0gJnzyAarlAJUQ+IL9zfE+paEHi154o5jWVdF5OITn8VxtBWj7yC9dn7IhyYP7p+11qNLhSk5AvHMSeVEGSXiTt7EnfMc/f2AnI12L0LFpu2VQbL5QasYJugVd4XQNIq5J+dPc+pTTVdRng0FRGN/oHM+zYkPnz5eLFR/wSqNmHS0yLcwO4L9HI=}
