matrix:
  - [[OSX_VARIANT, 'native']]
  - [[OSX_VARIANT, 'pocl']]

travis:
  secure:
    BINSTAR_TOKEN: P+BGWXYnRpwKj9ZXPgBhYVTh29xbUigLgl8/7q3fIsr67SQsWuTnM/9wsyZGIBhaC1M3rTmwIq3YBSUZU0/UV5OL++puJUMg2C+q7yKUVuHKiGQnQtcHtOZD0iUl0g/4xQ8s1a7BcO2JBoVCCnhZERYTEoATLDcBaNvA1tvULnDwAwZEZe2XRUGJ5slOINzvTdl+lhVzUYTPfc8jRoL42isWaFiQM9kTIZ5cWgnjO5wuunN2NMCDWAqxUKZCLr17nSs3ikuKzPnvUvU6ZwKcREh82cD2VH0G19dPm5rlubiOh0YCDytwIlqk4wWLBvxC/MP9kDdSxK2yuxkS5+9JZX1yCpY3n9fpQghtVBInjnH4niWUOZRUnl8i9lCUPI6SO2BPIJoHhDgWTQQWd7UcQ7Lh4iWp8a0r2Vniy2eJFqckJ5+kGtb8lGLrA2K+oWNIXvSTgT4NN6GUfhwYK7DJ3coqkka4H9hYp8IZPMUjAJogXA0Uox/TRyFrLbPr3whVMG+DcsrJpaLE4JYmgIAs9ccVdKkuxgjtVoYlPJRr3NrFeIlR4mrx+kyL+8tYXEoAoNu10kCGOi/N+kN4I/U2QywK531fnZmXYHsj2UunxTyVWkSRUGjej62w37bfTEHIdLSq5t3YZQmdIbtKa4iGnUnnjIItRGyrkzRu9ZdBVPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
